### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by eried** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#233]
hi! is there any particular reason for not using the esp32? I still havent received my pcb and I know it takes a lot of effort in general (that is basically why I did not wanted to start my own journey and have the pump half assembled forever lol).

My electricity company offers an api with the current price per kw, and some log of past values so if there is enough power some simple prediction could be happening during the nights... however I remember the esp8266 struggle a bit just with handling of a non open AP

**Comment by visualapproach** [comment]
Some versions of ESP32 have hardware bugs in edge triggered interrupts. I never got it to work, probably because I had that issue, but I'm not sure. There is some workarounds for that particular problem but I couldn't be bothered. Possibly it will work on the 4 wire versions depending on how the softserial library handles that.
I don't think your extra code would need to choke the ESP8266. You also have an extra 80 MHz to throw in if you need.
