### ISSUE TITLE
Hydrojets are displayed although MIAMI2021 was selected

### ISSUE THREAD

**Issue by johanneslasnik** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#270]
I have reflashed several times now, yet the hydrojets keep popping up. 
Also, the button is not in line with the others.

![Screenshot](https://user-images.githubusercontent.com/47891664/167806926-198f71b6-aa79-4905-825e-8e922d58e58f.png)

**Comment by visualapproach** [comment]
Alignment should be fixed in development branch. You only need to upload "websocket.js" file.
The hydrojets button will only show immidiately after page loading, and then only when receiving HASJETS:TRUE. Only way it receives HASJETS:TRUE is if you defined a model with hydrojets in "model.h", or if you explicitly change the "BWC_8266_globals.h":
```
#elif defined(MIAMI2021)
const uint16_t ButtonCodes[] =
{
  0x1B1B, 0x0100, 0x0300, 0x1212, 0x0809, 0x1012, 0x1112, 0x1312, 0x0200, 0x0000
};
const bool HASJETS = false;
```

Please check the console in the browser:
![image](https://user-images.githubusercontent.com/22987250/167901526-7f8666bd-4e2d-4a6f-8880-0c07360a6a0b.png)

**Comment by visualapproach** [comment]
Update to dev branch 2022-05-11. I see that it says Hasjets:'0' instead of Hasjets:false.
It's a bug in your version.

**Comment by visualapproach** [comment]
Actually it seems that 2022-04-11 shouldn't send '0' as a string. Maybe you downloaded just before I fixed it and I maybe didn't update the version date? Strange but try compiling/uploading the today version and see.

**Comment by johanneslasnik** [comment]
Yep, working now!
Thank you

![2022-05-11 21_57_40-Lay-Z-Spa Module](https://user-images.githubusercontent.com/47891664/167935486-4495d849-3da6-482f-b4cd-11752f5b7a30.png)

**Comment by visualapproach** [comment]
No problem 🤝
