### ISSUE TITLE
"Wifi Timer"? No connection after 9pm

### ISSUE THREAD

**Issue by AcobolTLP** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#515]
Hey guys, I'm having an issue with my ESP32 running your code. 
The acess is working when I'm using layzspa.local in my browser. But every day around 9pm that's not working, just giving me the issue "DNS_PROBE_FINISHED_NXDOMAIN" until 7 or 8am.

The wifi and internet connection are okay. Is there some kind of "wifi timer" in your code for saving energy or something else? 
The spa is working when pressing the button, but the ESP is then still not available.

Greets vom bavaria!
Markus

**Comment by visualapproach** [comment]
Hi, I presume you mean ESP8266.
There is no wifi timer like that. The problem is likely in your network. It can't resolve the DNS .local. Try entering the IP instead and see if that works.
[Google search dns_probe_finished_nxdomain](https://kinsta.com/knowledgebase/dns_probe_finished_nxdomain/)
Hope you find the fault.
